[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "driver_composer"
description = "i2c driver composer for different IC"
dynamic = ["version"]
readme = "README.md"

classifiers = [
]
license = {text = "MIT license"}

dependencies = [
    "smbus2",
]

[project.optional-dependencies]
ui = ["flask", "python-dotenv"]
ai = [
  "Jinja2",
  "typer",
  "aiofiles",
  "langchain",
  "langchain-community",
  "langgraph",
  "langchain-openai",
  "langgraph-cli",
  "rank_bm25",
  "pypdf",
  "nltk",
  "pydantic-settings"
]

[tool.setuptools_scm]
version_file = "_version.py"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["*.*"]

[tool.ruff]
line-length = 119


