[tox]

[testenv]
base_python = 3.12
package = editable

[testenv:dev]
deps = 
    ruff 
    pytest

[testenv:quality]
deps = 
    ruff
    codespell
commands = 
    ruff check
    ruff format --check
    codespell

[testenv:test]
deps = pytest
commands = 
    pytest tests -s {posargs}
