# This driver is generated by driver-composer. Do not edit directly.

from driver_composer.driver import Driver
from driver_composer.register import BitField, RegXX


class REG00(RegXX):
    EN_VIN_TRK = BitField(width=1, default=1)
    """
    Enable VIN_LIM tracking of VBATT: 0=fixed VIN_LIM, 1=VIN_LIM is max(VIN_LIM
    setting, VBATT+165mV)
    """
    SW_FREQ = BitField(width=2, default=1)
    """
    Buck/boost switching frequency selection: 00=750kHz, 01=1MHz, 10=1.25MHz,
    11=1.5MHz
    """
    HOLDOFF_TMR = BitField(width=1, default=1)
    """
    Enable/disable input hold-off timer before DP/DM detection
    """
    LOCK_CHG = BitField(width=1, default=0)
    """
    Lock charge parameter RegXXs (VBATT, ICC, IPRE, JEITA_VSET, JEITA_ISET) to
    only allow equal or lower values
    """
    EN_PG_NTC2 = BitField(width=1, default=0)
    """
    Select PG/NTC2 pin function: 0 = PG power-good, 1 = NTC2 thermistor input
    """
    EN_STAT_IB = BitField(width=1, default=0)
    """
    Select STAT/IB pin function: 0 = STAT open-drain status, 1 = IB analog current
    output
    """
    REG_RST = BitField(width=1, default=0)
    """
    Reset RegXXs to default values when written 1; self-clears to 0
    """


class REG01(RegXX):
    IIN_LIM = BitField(width=5, default=4)
    """
    Input current limit setting, step 100mA, range 100mA–3.2A (encoded as
    100mA×code). Default 500mA (00100). Auto-updated from DP/DM and CC detection;
    host may overwrite.
    """
    IIN_MODE = BitField(width=3, default=0)
    """
    Input current limit control: 000=follow IIN_LIM[4:0] (auto from detection),
    001=100mA, 010=500mA, 011=900mA, 100=1500mA, 101=2000mA, 110=3000mA
    """


class REG02(RegXX):
    ICC = BitField(width=6, default=25)
    """
    Fast charge current setting, step 80mA, range 0–5A (80mA×code). Default 2A
    (011001).
    """
    VPRE = BitField(width=2, default=3)
    """
    Pre-charge to fast-charge VBATT threshold: 00=2.4V, 01=2.6V, 10=2.8V, 11=3.0V
    """


class REG03(RegXX):
    ITERM = BitField(width=4, default=3)
    """
    Charge termination current, range 30–480mA, offset 30mA, step 30mA
    (I=30mA+30mA×code). Default 120mA (0011).
    """
    IPRE = BitField(width=4, default=4)
    """
    Pre-charge current, range 80–680mA, offset 80mA, step 40mA (I=80mA+40mA×code).
    Default 240mA (0100).
    """


class REG04(RegXX):
    VIN_LIM = BitField(width=4, default=6)
    """
    Input minimum voltage regulation threshold, VIN_LIM = 3.88V + (code×80mV),
    range 3.88–5.08V. Default 4.36V (0110).
    """
    ITRICKLE = BitField(width=3, default=3)
    """
    Trickle charge current, range 32–256mA, offset 32mA, step 32mA
    (I=32mA×(code+1)). Default 128mA (011).
    """
    VRECHG = BitField(width=1, default=0)
    """
    Auto-recharge threshold below VBATT_REG: 0=100mV, 1=200mV
    """


class REG05(RegXX):
    VBATT = BitField(width=6, default=24)
    """
    Battery regulation voltage VBATT_REG, range 3.6–4.6V in 25mV steps
    (VBATT=3.6V+25mV×code), values >4.6V are clamped. Default 4.2V (011000).
    """
    TOPOFF_TMR = BitField(width=2, default=0)
    """
    Top-off timer after termination: 00=disabled, 01=15min, 10=30min, 11=45min
    """


class REG06(RegXX):
    TREG = BitField(width=3, default=4)
    """
    Charge-mode thermal regulation / boost OTP threshold: 000=60°C, 001=70°C,
    010=80°C, 011=90°C, 100=100°C, 101=110°C, 110=120°C. Default 100°C (100).
    """
    SYS_MIN = BitField(width=3, default=4)
    """
    System minimum regulation VSYS_MIN: 000=2.975V, 001=3.15V, 010=3.325V,
    011=3.5V, 100=3.588V, 101=3.675V, 110=3.763V. Actual VSYS target is
    VSYS_MIN+VTRACK (≈150mV). Default 3.588V (100).
    """
    VIN_OVP = BitField(width=2, default=0)
    """
    Input over-voltage protection threshold: 00=6.3V, 01=11V, 10=14V, 11=disabled
    """


class REG07(RegXX):
    CHG_TIMER = BitField(width=2, default=2)
    """
    Charge safety timer (pre+fast after VBATT>VPRE): 00=disabled, 01=5h, 10=10h,
    11=15h. Default 10h (10).
    """
    EN_TMR2X = BitField(width=1, default=1)
    """
    Enable 2× slow counting of charge safety timer in DPM/thermal/JEITA derating:
    0=normal, 1=half-rate
    """
    EN_TERM = BitField(width=1, default=1)
    """
    Enable charge termination: 0=disable, 1=enable
    """
    WATCHDOG = BitField(width=2, default=1)
    """
    Watchdog timer period: 00=disabled, 01=40s, 10=80s, 11=160s. Default 40s (01).
    """
    WATCHDOG_RST = BitField(width=1, default=0)
    """
    Write 1 to reset watchdog timer; self-clears to 0
    """
    IB_EN = BitField(width=1, default=0)
    """
    IB output enable when only battery present: 0=IB only when switcher on, 1=IB
    always on (adds ~3µA from battery)
    """


class REG08(RegXX):
    VBOOST = BitField(width=3, default=7)
    """
    Boost output voltage: 011=5.35V, 010=5.30V, 001=5.25V, 000=5.20V, 111=5.15V,
    110=5.10V, 101=5.05V, 100=5.00V. Default 5.15V (111).
    """
    OLIM = BitField(width=2, default=3)
    """
    Boost output current limit: 00=500mA, 01=1.5A, 10=2.1A, 11=3A. Default 3A (11).
    """
    BATTFET_RST_EN = BitField(width=1, default=1)
    """
    Enable RST-pin BATTFET reset function (system reset): 0=disable, 1=enable
    """
    BATTFET_DLY = BitField(width=1, default=1)
    """
    Delay before turning BATTFET off after BATTFET_DIS=1: 0=immediate, 1=10s delay
    """
    BATTFET_DIS = BitField(width=1, default=0)
    """
    Disable BATTFET (shipping/OCP): 0=allow BATTFET on, 1=turn BATTFET off
    (immediately or after delay)
    """


class REG09(RegXX):
    EN_CHG = BitField(width=1, default=1)
    """
    Charging permission: 0=force charging off, 1=charging allowed
    """
    EN_BUCK = BitField(width=1, default=1)
    """
    Buck converter permission: 0=force buck off, 1=buck allowed
    """
    EN_BOOST = BitField(width=1, default=0)
    """
    Boost converter enable (behavior depends on AUTOOTG): 0=disable boost, 1=enable
    boost
    """
    AUTOOTG = BitField(width=1, default=1)
    """
    Automatic OTG control: 0=host controls boost via EN_BOOST, 1=boost auto-
    controlled by CC detection
    """
    CC_CFG = BitField(width=3, default=0)
    """
    Type‑C CC mode: 000=sink only, 001=source only, 010=DRP, 011=DRP with Try.SNK,
    100=DRP with Try.SRC, 101=CC disabled. Mode changes reset state to
    Unattached.SNK. Default sink only (000).
    """

    Reserved = BitField(width=1, default=0)


class REG0A(RegXX):
    FORCE_CC = BitField(width=2, default=0)
    """
    Override CC pin behavior: 00=auto per CC_CFG, 01=force Rd, 10=force Rp (per
    RP_CFG), 11=force Hi‑Z
    """
    RP_CFG = BitField(width=2, default=1)
    """
    Type‑C source Rp current advertisement: 00=80µA (default USB), 01=180µA (1.5A),
    10=330µA (3A). Default 01.
    """
    FORCEDPDM = BitField(width=1, default=0)
    """
    Start D+/D− detection immediately when written 1; self-clears to 0
    """
    AUTODPDM = BitField(width=1, default=1)
    """
    Automatic D+/D− detection: 0=only when FORCEDPDM=1, 1=auto after VIN_GD=1 and
    hold-off timer
    """

    Reserved = BitField(width=2, default=0)


class REG0B(RegXX):
    HVREQ = BitField(width=2, default=0)
    """
    DP/DM static levels after HV charger detection (DPDM_STAT=1001): 00: DP=0.6V,
    DM=Hi‑Z; 01: DP=3.3V, DM=0.6V; 10: DP=0.6V, DM=0.6V; 11: DP=0.6V, DM=3.3V.
    Reset to 00 when VIN_GD=0.
    """
    HVDOWN = BitField(width=1, default=0)
    """
    When written 1 (with DPDM_STAT=1001 and HVREQ=11): drive DP=DM=0.6V for 500µs;
    self-clears to 0
    """
    HVUP = BitField(width=1, default=0)
    """
    When written 1 (with DPDM_STAT=1001 and HVREQ=11): drive DP=DM=3.3V for 500µs;
    self-clears to 0
    """
    HVEN = BitField(width=1, default=1)
    """
    Enable high‑voltage adapter detection on DP/DM
    """

    Reserved = BitField(width=3, default=0)


class REG0C(RegXX):
    BOOST_OTP_EN = BitField(width=1, default=1)
    """
    Boost over-temperature protection behavior: 0=ignore boost OTP, 1=stop and
    latch boost at TREG
    """
    BOOST_STP_EN = BitField(width=1, default=0)
    """
    Boost stop on BATT_LOW: 0=only generate INT, 1=turn off boost and latch when
    VBATT<BATT_LOW
    """
    BATT_LOW = BitField(width=2, default=0)
    """
    Battery-low comparator falling threshold: 00=3.0V, 01=3.1V, 10=3.2V, 11=3.3V.
    200mV hysteresis.
    """
    BATT_OVP_EN = BitField(width=1, default=1)
    """
    Battery over-voltage protection enable
    """
    NTC2_ACTION = BitField(width=1, default=0)
    """
    NTC2 behavior: 0=only generate INT on status change, 1=full JEITA and
    protection action enabled
    """
    NTC1_ACTION = BitField(width=1, default=1)
    """
    NTC1 behavior: 0=only generate INT on status change, 1=full JEITA and
    protection action enabled
    """

    Reserved = BitField(width=1, default=0)


class REG0D(RegXX):
    JEITA_ISET = BitField(width=2, default=0)
    """
    JEITA reduced current fraction of ICC: 00=50%, 01=33%, 10=20%
    """
    JEITA_VSET = BitField(width=2, default=0)
    """
    JEITA reduced voltage offset from VBATT_REG: 00=−100mV, 01=−150mV, 10=−200mV,
    11=−250mV
    """
    COOL_ACT = BitField(width=2, default=2)
    """
    Action in cool range: 00=no action, 01=reduce VBATT_REG, 10=reduce ICC,
    11=reduce both
    """
    WARM_ACT = BitField(width=2, default=1)
    """
    Action in warm range: 00=no action, 01=reduce VBATT_REG, 10=reduce ICC,
    11=reduce both
    """


class REG0E(RegXX):
    VCOLD = BitField(width=2, default=1)
    """
    Cold rising threshold as % of VVRNTC: 00=78.4% (≈−5°C), 01=74.2% (≈0°C),
    10=69.6% (≈5°C), 11=64.8% (≈10°C). Default 74.2% (01).
    """
    VCOOL = BitField(width=2, default=2)
    """
    Cool rising threshold as % of VVRNTC: 00=74.2% (≈0°C), 01=69.6% (≈5°C),
    10=64.8% (≈10°C), 11=59.9% (≈15°C). Default 64.8% (10).
    """
    VWARM = BitField(width=2, default=1)
    """
    Warm falling threshold as % of VVRNTC: 00=36.5% (≈40°C), 01=32.6% (≈45°C),
    10=29.1% (≈50°C), 11=25.9% (≈55°C). Default 32.6% (01).
    """
    VHOT = BitField(width=2, default=2)
    """
    Hot falling threshold as % of VVRNTC: 00=29.1% (≈50°C), 01=25.9% (≈55°C),
    10=23% (≈60°C), 11=20.4% (≈65°C). Default 23% (10).
    """


class REG0F(RegXX):
    VIN_TEST = BitField(width=2, default=0)
    """
    VIN test comparator threshold: 00=0.3V, 01=0.5V, 10=1.0V, 11=1.5V
    """
    IVIN_SRC = BitField(width=4, default=0)
    """
    VIN test source current: 0000=5µA, 0001=10µA, 0010=20µA, 0011=40µA, 0100=80µA,
    0101=160µA, 0110=320µA, 0111=640µA, 1000=1280µA
    """
    VIN_SRC_EN = BitField(width=1, default=0)
    """
    Enable VIN source current for input impedance test
    """

    Reserved = BitField(width=1, default=0)


class REG10(RegXX):
    MASK_DEBUG_AUDIO = BitField(width=1, default=0)
    """
    Mask DEBUGACC and AUDIOACC INTs
    """
    MASK_BATT_LOW = BitField(width=1, default=0)
    """
    Mask BATT_LOW_STAT INT
    """
    MASK_CC_INT = BitField(width=1, default=0)
    """
    Mask CC_SNK_STAT and CC_SRC_STAT INTs
    """
    MASK_TOPOFF = BitField(width=1, default=0)
    """
    Mask TOPOFF timer start/end INT
    """
    MASK_DPM = BitField(width=1, default=0)
    """
    Mask VINDPM_STAT and IINDPM_STAT INTs
    """
    MASK_THERM = BitField(width=1, default=0)
    """
    Mask THERM_STAT INT
    """

    Reserved = BitField(width=2, default=0)


class REG11(RegXX):
    IINDPM_STAT = BitField(width=1, default=0)
    """
    Input current DPM status: 0=not in IIN_LIM loop, 1=in IIN_LIM loop
    """
    VINDPM_STAT = BitField(width=1, default=0)
    """
    Input voltage DPM status: 0=not in VIN_LIM loop, 1=in VIN_LIM loop
    """

    Reserved = BitField(width=2)

    DPDM_STAT = BitField(width=4, default=0)
    """
    DP/DM input source type result: 0000=not started(500mA), 0001=USB SDP(500mA),
    0010=USB DCP(2A), 0011=USB CDP(1.5A), 0100=Divider1(1A), 0101=Divider2(2.1A),
    0110=Divider3(2.4A), 0111=Divider4(2A), 1000=unknown(500mA), 1001=high‑voltage
    adapter(2A), 1110=Divider5(3A)
    """


class REG12(RegXX):
    WATCHDOG_BARK = BitField(width=1, default=0)
    """
    Watchdog bark (3/4 of timer elapsed)
    """
    WATCHDOG_FAULT = BitField(width=1, default=0)
    """
    Watchdog timeout occurred
    """
    VSYS_STAT = BitField(width=1, default=0)
    """
    System voltage status vs VSYS_MIN: 0=VBATT<VSYS_MIN, 1=VBATT>VSYS_MIN
    """
    THERM_STAT = BitField(width=1, default=0)
    """
    Charge thermal regulation active: 0=not in thermal regulation, 1=in thermal
    regulation
    """
    LEGACYCABLE = BitField(width=1, default=0)
    """
    Legacy Type‑A to Type‑C cable detected (not valid in DRP mode)
    """
    VIN_RDY = BitField(width=1, default=0)
    """
    Input source type detection done and IIN_LIM updated; VIN ready for charging
    """
    VIN_GD = BitField(width=1, default=0)
    """
    Valid input source: 0=VIN invalid, 1=VIN between VIN_UV and VIN_OV (after
    debounce), PG asserted low if EN_PG_NTC2=0
    """

    Reserved = BitField(width=1)


class REG13(RegXX):
    CHG_FAULT = BitField(width=2, default=0)
    """
    Charge fault code: 00=normal, 01=input OVP, 10=charge timer expired, 11=battery
    OVP
    """
    BOOST_FAULT = BitField(width=3, default=0)
    """
    Boost fault code: 000=normal, 001=IN overload or short (latch‑off), 010=boost
    OVP (non‑latched), 011=boost OTP (latch‑off), 100=boost stopped due to BATT_LOW
    (latch‑off)
    """
    CHG_STAT = BitField(width=3, default=0)
    """
    Charge status: 000=not charging, 001=trickle, 010=pre‑charge, 011=fast charge
    (CC), 100=constant‑voltage (CV), 101=charging done
    """


class REG14(RegXX):
    NTC2_FAULT = BitField(width=3, default=0)
    """
    NTC2 temperature status: 000=normal, 001=warm, 010=cool, 011=cold, 100=hot
    """
    NTC1_FAULT = BitField(width=3, default=0)
    """
    NTC1 temperature status: 000=normal, 001=warm, 010=cool, 011=cold, 100=hot
    """
    BATT_MISSING = BitField(width=1, default=0)
    """
    Battery missing (two terminations detected within 3s)
    """
    NTC_MISSING = BitField(width=1, default=0)
    """
    NTC missing (VNTC > 95% of VVRNTC)
    """


class REG15(RegXX):
    CC2_SRC_STAT = BitField(width=2, default=0)
    """
    CC2 source‑side CC status: 00=vOPEN, 01=vRd detected, 10=vRa detected
    """
    CC1_SRC_STAT = BitField(width=2, default=0)
    """
    CC1 source‑side CC status: 00=vOPEN, 01=vRd detected, 10=vRa detected
    """
    CC2_SNK_STAT = BitField(width=2, default=0)
    """
    CC2 sink detection: 00=vRa, 01=vRd‑USB, 10=vRd‑1.5A, 11=vRd‑3.0A
    """
    CC1_SNK_STAT = BitField(width=2, default=0)
    """
    CC1 sink detection: 00=vRa (no source), 01=vRd‑USB (default current),
    10=vRd‑1.5A, 11=vRd‑3.0A
    """


class REG16(RegXX):
    AUDIOACC = BitField(width=1, default=0)
    """
    Entered AudioAccessory state
    """
    DEBUGACC = BitField(width=1, default=0)
    """
    Entered DebugAccessory.SNK state
    """
    VIN_TEST_HIGH = BitField(width=1, default=0)
    """
    VIN reached VIN_TEST threshold during input impedance test
    """
    OTG_NEED = BitField(width=1, default=0)
    """
    Boost requirement indication for host when AUTOOTG=0: 0=boost should be
    disabled, 1=boost should be enabled
    """
    BATT_LOW_STAT = BitField(width=1, default=0)
    """
    Battery below BATT_LOW threshold (with 200mV hysteresis)
    """
    BFET_STAT = BitField(width=1, default=0)
    """
    Battery FET direction: 0=battery charging or disabled, 1=battery discharging
    """
    TOPOFF_ACTIVE = BitField(width=1, default=0)
    """
    Top‑off timer status: 0=not counting, 1=top‑off timer running
    """

    Reserved = BitField(width=1)


class MP2722(Driver):
    REG00 = REG00()
    REG01 = REG01()
    REG02 = REG02()
    REG03 = REG03()
    REG04 = REG04()
    REG05 = REG05()
    REG06 = REG06()
    REG07 = REG07()
    REG08 = REG08()
    REG09 = REG09()
    REG0A = REG0A()
    REG0B = REG0B()
    REG0C = REG0C()
    REG0D = REG0D()
    REG0E = REG0E()
    REG0F = REG0F()
    REG10 = REG10()
    REG11 = REG11()
    REG12 = REG12()
    REG13 = REG13()
    REG14 = REG14()
    REG15 = REG15()
    REG16 = REG16()

    def __init__(self, i2c, device_address=0):
        super().__init__(i2c, device_address)
